server {
    listen 80;
    server_name si-api.ucak.sn auth.ucak.sn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name si-api.ucak.sn;
    root /var/www/html/public;

    index index.php;

    client_max_body_size 10M;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ssl_certificate     /etc/letsencrypt/live/si-api.ucak.sn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/si-api.ucak.sn/privkey.pem;


    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

server {
    listen 443 ssl;
    server_name auth.ucak.sn;

    ssl_certificate     /etc/letsencrypt/live/si-api.ucak.sn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/si-api.ucak.sn/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://keycloak:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port 443;
    }
}
