<?php

namespace App\Support;

final class PermissionCatalog
{
    public const ROLES = ['ADMIN', 'STAFF', 'FACULTY', 'STUDENT'];

    /** @return array<int, string> */
    public static function permissions(): array
    {
        return [
            // Academic structure
            'faculties.view',
            'faculties.create',
            'faculties.update',
            'faculties.delete',
            'departments.view',
            'departments.create',
            'departments.update',
            'departments.delete',
            'academic_programs.view',
            'academic_programs.create',
            'academic_programs.update',
            'academic_programs.delete',
            'academic_years.view',
            'academic_years.create',
            'academic_years.update',
            'academic_years.delete',
            'course_units.view',
            'course_units.create',
            'course_units.update',
            'course_units.delete',
            'courses.view',
            'courses.create',
            'courses.update',
            'courses.delete',
            'faculty_members.view',
            'faculty_members.create',
            'faculty_members.update',
            'faculty_members.delete',
            'course_enrollments.view',
            'course_enrollments.create',
            'course_enrollments.update',
            'course_enrollments.delete',
            'admins.view',
            'admins.create',
            'admins.update',
            'admins.delete',
            'guardians.view',
            'guardians.create',
            'guardians.update',
            'guardians.delete',

            // Enrollment & student records
            'enrollments.view',
            'enrollments.create',
            'enrollments.update',
            'enrollments.delete',
            'registrations.view',
            'registrations.create',
            'registrations.update',
            'registrations.delete',
            'student_records.view',
            'student_records.update',
            'students.view',
            'students.create',
            'students.update',
            'students.delete',
            'student_profiles.view',
            'student_profiles.update',

            // Grades & deliberations
            'grades.view',
            'grades.create',
            'grades.update',
            'grades.delete',
            'grades.submit',
            'grades.validate',
            'grades.publish',
            'assessments.view',
            'assessments.create',
            'assessments.update',
            'assessments.delete',
            'deliberations.view',
            'deliberations.create',
            'deliberations.update',
            'deliberations.delete',
            'deliberation_results.view',
            'deliberation_results.create',
            'deliberation_results.update',
            'deliberation_results.delete',
            'transcripts.view',
            'transcripts.create',
            'transcripts.update',
            'transcripts.delete',
            'semester_results.view',
            'semester_results.create',
            'semester_results.update',
            'semester_results.delete',
            'semester_results.calculate',

            // Finance
            'invoices.view',
            'invoices.create',
            'invoices.update',
            'invoices.delete',
            'payments.view',
            'payments.create',
            'payments.update',
            'payments.delete',
            'scholarships.view',
            'scholarships.create',
            'scholarships.update',
            'scholarships.delete',

            // Documents
            'documents.view',
            'documents.create',
            'documents.update',
            'documents.delete',
            'documents.review',
            'documents.download',
            'document_requests.view',
            'document_requests.create',
            'document_requests.update',
            'document_requests.delete',
            'generated_documents.view',
            'generated_documents.create',
            'generated_documents.update',
            'generated_documents.delete',

            // Operations
            'attendance.view',
            'attendance.create',
            'attendance.update',
            'attendance.delete',
            'timetables.view',
            'timetables.create',
            'timetables.update',
            'timetables.delete',
            'reports.view',
            'reports.create',
            'reports.update',
            'reports.delete',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'notifications.delete',
            'announcements.view',
            'announcements.create',
            'announcements.update',
            'announcements.delete',
            'audits.view',

            // Administration
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.assign_roles',
            'roles.view',
            'roles.manage',
            'permissions.view',
            'settings.view',
            'settings.update',
        ];
    }

    /** @return array<string, array<int, string>> */
    public static function rolePermissions(): array
    {
        $allPermissions = self::permissions();

        return [
            'ADMIN' => $allPermissions,
            'STAFF' => [
                'faculties.view',
                'departments.view',
                'academic_programs.view',
                'course_units.view',
                'courses.view',
                'course_enrollments.view',
                'course_enrollments.create',
                'course_enrollments.update',
                'enrollments.view',
                'enrollments.create',
                'enrollments.update',
                'registrations.view',
                'registrations.create',
                'registrations.update',
                'student_records.view',
                'students.view',
                'students.create',
                'students.update',
                'grades.view',
                'grades.create',
                'grades.update',
                'transcripts.view',
                'semester_results.view',
                'faculty_members.view',
                'guardians.view',
                'admins.view',
                'documents.view',
                'documents.create',
                'documents.update',
                'documents.review',
                'documents.download',
                'document_requests.view',
                'document_requests.create',
                'document_requests.update',
                'generated_documents.view',
                'notifications.view',
                'notifications.create',
                'notifications.update',
                'announcements.view',
                'announcements.create',
                'announcements.update',
                'invoices.view',
                'invoices.create',
                'invoices.update',
                'payments.view',
                'payments.create',
                'payments.update',
                'reports.view',
                'settings.view',
            ],
            'FACULTY' => [
                'faculties.view',
                'departments.view',
                'academic_programs.view',
                'course_units.view',
                'courses.view',
                'courses.create',
                'courses.update',
                'assessments.view',
                'assessments.create',
                'assessments.update',
                'grades.view',
                'grades.create',
                'grades.update',
                'grades.submit',
                'deliberations.view',
                'semester_results.view',
                'attendance.view',
                'attendance.create',
                'attendance.update',
                'course_enrollments.view',
                'course_enrollments.create',
                'faculty_members.view',
                'guardians.view',
                'reports.view',
            ],
            'STUDENT' => [
                'faculties.view',
                'departments.view',
                'academic_programs.view',
                'course_units.view',
                'courses.view',
                'enrollments.view',
                'registrations.view',
                'grades.view',
                'transcripts.view',
                'semester_results.view',
                'student_profiles.view',
                'guardians.view',
                'documents.view',
                'document_requests.view',
                'document_requests.create',
                'generated_documents.view',
                'notifications.view',
                'reports.view',
            ],
        ];
    }
}
